### ISSUE TITLE
Bug: Only the account that added in genesis can sign the txs

### ISSUE THREAD

**Issue by freddyli7** [ChainSafe/chainlink-cosmos#48]
when trying to add new module owner and sign the tx with account that is not in genesis account list, got error `rpc error: key not found`

How to reproduce: 
check out master branch
run `make all`
send a new module owner tx and sign it by any account that is not in genesis account list

Error:
`Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account cosmos1gsphfm2j640hlsq5mqkxrz6zrj670uqfgneju0 not found: key not found
`

**Comment by araskachoi** [comment]
i believe this is expected behavior. the local key in keychain technically does not exist on the cosmos network until a valid account has sent some funds to that address. this is because there is not state that exists for that address until someone sends funds to it. i think we encountered this in ethermint as well but there is no workaround besides sending a tx to set that account to the chain state

**Comment by freddyli7** [comment]
Tested with txs and seems this bug has been fixed.

To sign and broadcast a tx, always make sure that there is enough link token in the account, then:

1. if tx is signed and broadcasted remotely, just make sure it has enough token in balance.
1. if tx is signed on the local of the node by CLI, the account must be added in the keyring.
